"""Canonical durable-knowledge models and helpers."""

from .artifact import (
    ARTIFACT_RETENTION_POLICIES,
    ARTIFACT_SOURCE_CLASSES,
    ArtifactRecord,
    ArtifactRetentionPolicy,
    ArtifactSourceClass,
)
from .block import (
    MEMORY_BLOCK_DEFERRED_MODES,
    MEMORY_BLOCK_V1_CLASS_ALLOWLIST,
    MEMORY_BLOCK_V1_MODES,
    MemoryBlock,
    MemoryBlockClass,
    MemoryBlockMode,
    validate_block_for_creation,
)
from .candidate import CandidateReview, MemoryCandidate
from .convergence import (
    FACT_ACTIVE_STATES,
    FactActiveState,
    FactConvergenceLink,
    RAW_EPISODE_KINDS,
    RawEpisode,
    RawEpisodeKind,
)
from .ontology import (
    CategorySchema,
    EdgeTypeSchema,
    EntityTypeSchema,
    ONTOLOGY_COMPATIBILITIES,
    OntologyCompatibility,
    OntologyDefinition,
    PROPERTY_VALUE_TYPES,
    PropertySchema,
    PropertyValueType,
)
from .entity_fact import (
    CONTRADICTION_DECISIONS,
    ENTITY_FACT_SOURCE_KINDS,
    Contradiction,
    ContradictionDecision,
    Entity,
    EntityAlias,
    EntityFactProvenance,
    EntityFactSourceKind,
    EntitySummary,
    Fact,
)
from .episode_procedure import (
    EPISODE_STATUSES,
    OUTCOME_STATUSES,
    PROCEDURE_PROMOTION_TIERS,
    STEP_KINDS,
    Decision,
    Episode,
    EpisodeStatus,
    EpisodeStep,
    Outcome,
    OutcomeStatus,
    Procedure,
    ProcedurePromotionTier,
    ProcedureStep,
    StepKind,
)
from .change import (
    ChangeObjectType,
    ChangeOperation,
    SophiaGraphChangeEvent,
    default_change_namespace,
)
from .document import (
    DocumentBlockType,
    DocumentSourceFormat,
    KnowledgeDocument,
    KnowledgeDocumentBlock,
    content_hash,
)
from .embedding import MemoryEmbedding, memory_embedding_from_dict
from .embedding_lifecycle import (
    EMBEDDING_STALENESS_REASONS,
    ActiveEmbeddingModelSet,
    EmbeddingStalenessReason,
    ReembedBatch,
    ReembedCursor,
    ReembedPlan,
    StaleEmbeddingFinding,
    VectorSpaceModelDescriptor,
    namespace_key,
)
from .link import (
    ContextUnit,
    ExplicitLinkResolver,
    LinkKind,
    LinkResolution,
    LinkResolutionCandidate,
    LinkResolutionDiagnostic,
    LinkResolutionStatus,
    StructuralLink,
    normalize_link_target,
    split_target_parts,
)
from .namespace import MemoryNamespace, MemoryNamespaceComponent, MemoryScope
from .storage_operations import (
    BACKUP_KINDS,
    BackupDescriptor,
    BackupIntegrityReport,
    BackupKind,
    BackupManifestEntry,
    CompactionOutcome,
    CompactionPlan,
    CoordinatedBackupManifest,
    MultiprocessLeaseToken,
    OperatorActionRequired,
    RestoreOptions,
    RestoreOutcome,
    RetentionSnapshot,
    RetentionSnapshotManifest,
)
from . import primitives as _primitive_models
from .primitives import (
    CandidateStatus,
    MemoryRelationType,
    MemorySource,
    MemoryTier,
    MemoryTierTransitionReason,
    MemoryType,
    NamespaceKind,
    RecordVisibility,
    RelationDirection,
    Scope,
    ScopeKind,
    SessionSummaryOutcome,
    SessionSummaryThreadStatus,
    coerce_candidate_status,
    coerce_memory_relation_type,
    coerce_memory_source,
    coerce_memory_tier,
    coerce_memory_tier_transition_reason,
    coerce_memory_type,
)
from .record import (
    ArtifactRef,
    MemoryPatchResult,
    MemoryRecord,
    RetrievalFilters,
    SessionSummaryActiveThread,
    SessionSummaryContent,
)
from . import record as _record_models
from .relation import MemoryRelation
from .tier import MemoryTierTransition

_SCOPE_PATTERN = _primitive_models._SCOPE_PATTERN
_as_candidate_status = _primitive_models._as_candidate_status
_as_claim_key_polarity = _primitive_models._as_claim_key_polarity
_as_memory_relation_type = _primitive_models._as_memory_relation_type
_as_memory_relation_type_list = _primitive_models._as_memory_relation_type_list
_as_memory_source = _primitive_models._as_memory_source
_as_memory_source_class = _primitive_models._as_memory_source_class
_as_memory_tier = _primitive_models._as_memory_tier
_as_memory_tier_transition_reason = _primitive_models._as_memory_tier_transition_reason
_as_memory_type = _primitive_models._as_memory_type
_as_memory_type_list = _primitive_models._as_memory_type_list
_coerce_temporal_dt = _record_models._coerce_temporal_dt

__all__ = [
    "ARTIFACT_RETENTION_POLICIES",
    "ARTIFACT_SOURCE_CLASSES",
    "ArtifactRecord",
    "ArtifactRef",
    "ArtifactRetentionPolicy",
    "ArtifactSourceClass",
    "CONTRADICTION_DECISIONS",
    "CandidateReview",
    "CandidateStatus",
    "Contradiction",
    "ContradictionDecision",
    "Decision",
    "ENTITY_FACT_SOURCE_KINDS",
    "EPISODE_STATUSES",
    "Entity",
    "EntityAlias",
    "EntityFactProvenance",
    "EntityFactSourceKind",
    "EntitySummary",
    "CategorySchema",
    "EdgeTypeSchema",
    "EntityTypeSchema",
    "FACT_ACTIVE_STATES",
    "FactActiveState",
    "FactConvergenceLink",
    "ONTOLOGY_COMPATIBILITIES",
    "OntologyCompatibility",
    "OntologyDefinition",
    "PROPERTY_VALUE_TYPES",
    "PropertySchema",
    "PropertyValueType",
    "RAW_EPISODE_KINDS",
    "RawEpisode",
    "RawEpisodeKind",
    "Episode",
    "EpisodeStatus",
    "EpisodeStep",
    "Fact",
    "OUTCOME_STATUSES",
    "Outcome",
    "OutcomeStatus",
    "PROCEDURE_PROMOTION_TIERS",
    "Procedure",
    "ProcedurePromotionTier",
    "ProcedureStep",
    "STEP_KINDS",
    "StepKind",
    "MEMORY_BLOCK_DEFERRED_MODES",
    "MEMORY_BLOCK_V1_CLASS_ALLOWLIST",
    "MEMORY_BLOCK_V1_MODES",
    "MemoryBlock",
    "MemoryBlockClass",
    "MemoryBlockMode",
    "validate_block_for_creation",
    "ChangeObjectType",
    "ChangeOperation",
    "ContextUnit",
    "DocumentBlockType",
    "DocumentSourceFormat",
    "EMBEDDING_STALENESS_REASONS",
    "EmbeddingStalenessReason",
    "ExplicitLinkResolver",
    "KnowledgeDocument",
    "KnowledgeDocumentBlock",
    "LinkKind",
    "LinkResolution",
    "LinkResolutionCandidate",
    "LinkResolutionDiagnostic",
    "LinkResolutionStatus",
    "MemoryCandidate",
    "MemoryEmbedding",
    "ActiveEmbeddingModelSet",
    "BACKUP_KINDS",
    "BackupDescriptor",
    "BackupIntegrityReport",
    "BackupKind",
    "BackupManifestEntry",
    "MemoryNamespace",
    "MemoryNamespaceComponent",
    "MemoryPatchResult",
    "MemoryRecord",
    "MemoryRelation",
    "MemoryRelationType",
    "MemoryScope",
    "MemorySource",
    "MemoryTier",
    "MemoryTierTransition",
    "MemoryTierTransitionReason",
    "MemoryType",
    "MultiprocessLeaseToken",
    "NamespaceKind",
    "OperatorActionRequired",
    "RecordVisibility",
    "ReembedBatch",
    "ReembedCursor",
    "ReembedPlan",
    "RelationDirection",
    "RetentionSnapshot",
    "RetentionSnapshotManifest",
    "RestoreOptions",
    "RestoreOutcome",
    "RetrievalFilters",
    "Scope",
    "ScopeKind",
    "SessionSummaryActiveThread",
    "SessionSummaryContent",
    "SessionSummaryOutcome",
    "SessionSummaryThreadStatus",
    "StructuralLink",
    "StaleEmbeddingFinding",
    "SophiaGraphChangeEvent",
    "VectorSpaceModelDescriptor",
    "CompactionOutcome",
    "CompactionPlan",
    "CoordinatedBackupManifest",
    "default_change_namespace",
    "memory_embedding_from_dict",
    "namespace_key",
    "coerce_candidate_status",
    "coerce_memory_relation_type",
    "coerce_memory_source",
    "coerce_memory_tier",
    "coerce_memory_tier_transition_reason",
    "coerce_memory_type",
    "content_hash",
    "normalize_link_target",
    "split_target_parts",
]
