"""Stable public surface for durable derived-index projection operations."""

from sophiagraph.models.projection import (
    ProjectionAttempt,
    ProjectionAttemptStatus,
    ProjectionBatchResult,
    ProjectionCheckpoint,
    ProjectionFailure,
    ProjectionFailureReason,
    ProjectionFinding,
    ProjectionFindingKind,
    ProjectionHealth,
    ProjectionInventoryItem,
    ProjectionLease,
    ProjectionReconciliationReport,
    ProjectionRepairAction,
    ProjectionRepairOperation,
    ProjectionRepairPlan,
    ProjectionTarget,
    ProjectionTargetKind,
)
from sophiagraph.projection import (
    ChangeProjector,
    GraphChangeProjector,
    ProjectionApplyStatus,
    ProjectionStateStore,
    VectorChangeProjector,
    get_projection_health,
    record_projection_health,
    run_projection_batch,
)
from sophiagraph.projection_reconciliation import (
    apply_projection_repair_plan,
    canonical_projection_inventory,
    reconcile_projection_target,
)

__all__ = [
    "ChangeProjector",
    "GraphChangeProjector",
    "ProjectionApplyStatus",
    "ProjectionAttempt",
    "ProjectionAttemptStatus",
    "ProjectionBatchResult",
    "ProjectionCheckpoint",
    "ProjectionFailure",
    "ProjectionFailureReason",
    "ProjectionFinding",
    "ProjectionFindingKind",
    "ProjectionHealth",
    "ProjectionInventoryItem",
    "ProjectionLease",
    "ProjectionReconciliationReport",
    "ProjectionRepairAction",
    "ProjectionRepairOperation",
    "ProjectionRepairPlan",
    "ProjectionStateStore",
    "ProjectionTarget",
    "ProjectionTargetKind",
    "VectorChangeProjector",
    "apply_projection_repair_plan",
    "canonical_projection_inventory",
    "get_projection_health",
    "record_projection_health",
    "reconcile_projection_target",
    "run_projection_batch",
]
