"""Stable facade for typed UI screens and screen-builder helpers."""

from sophiagraph.ui.screen_builders import (
    build_candidate_review_screen,
    build_community_structure_screen,
    build_explorer_screen,
    build_graph_view_screen,
    build_operations_console_screen,
    build_record_detail_packet,
    build_record_detail_screen,
    build_repair_center_screen,
    build_saved_view_workbench_screen,
    build_schema_developer_screen,
    build_timeline_screen,
)
from sophiagraph.ui.screen_types import (
    CandidateReviewScreen,
    CommunityStructureScreen,
    GraphViewMode,
    GraphViewRequest,
    GraphViewScreen,
    KnowledgeExplorerScreen,
    KnowledgeRecordDetailPacket,
    OperationsConsoleScreen,
    RecordDetailScreen,
    RepairCenterScreen,
    SavedViewWorkbenchPanel,
    SavedViewWorkbenchRequest,
    SavedViewWorkbenchScreen,
    SchemaDeveloperScreen,
    ScreenId,
    TimelineScreen,
    screen_to_dict,
)

__all__ = [
    "CandidateReviewScreen",
    "CommunityStructureScreen",
    "GraphViewMode",
    "GraphViewRequest",
    "GraphViewScreen",
    "KnowledgeExplorerScreen",
    "KnowledgeRecordDetailPacket",
    "OperationsConsoleScreen",
    "RecordDetailScreen",
    "RepairCenterScreen",
    "SavedViewWorkbenchPanel",
    "SavedViewWorkbenchRequest",
    "SavedViewWorkbenchScreen",
    "SchemaDeveloperScreen",
    "ScreenId",
    "TimelineScreen",
    "build_candidate_review_screen",
    "build_community_structure_screen",
    "build_explorer_screen",
    "build_graph_view_screen",
    "build_operations_console_screen",
    "build_record_detail_packet",
    "build_record_detail_screen",
    "build_repair_center_screen",
    "build_saved_view_workbench_screen",
    "build_schema_developer_screen",
    "build_timeline_screen",
    "screen_to_dict",
]
